// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhm4uEAgDU4L0wqvsl3goDmQo-AhsIh_k',
    appId: '1:959118139759:web:8deca9bdf96aafa4c8089a',
    messagingSenderId: '959118139759',
    projectId: 'flutter-firebase-18db2',
    authDomain: 'flutter-firebase-18db2.firebaseapp.com',
    storageBucket: 'flutter-firebase-18db2.appspot.com',
    measurementId: 'G-BMYHCTE5WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5K6f2P-O6ileNCxWnkZ7KzSFeMg4b0OM',
    appId: '1:959118139759:android:b0405d2da7b9721ec8089a',
    messagingSenderId: '959118139759',
    projectId: 'flutter-firebase-18db2',
    storageBucket: 'flutter-firebase-18db2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxwe8lm0kKsMAiKnJOUVZVubA5gHB7gb0',
    appId: '1:959118139759:ios:0f8a0ef484652b03c8089a',
    messagingSenderId: '959118139759',
    projectId: 'flutter-firebase-18db2',
    storageBucket: 'flutter-firebase-18db2.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxwe8lm0kKsMAiKnJOUVZVubA5gHB7gb0',
    appId: '1:959118139759:ios:0f8a0ef484652b03c8089a',
    messagingSenderId: '959118139759',
    projectId: 'flutter-firebase-18db2',
    storageBucket: 'flutter-firebase-18db2.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhm4uEAgDU4L0wqvsl3goDmQo-AhsIh_k',
    appId: '1:959118139759:web:0f316d7d0041841ac8089a',
    messagingSenderId: '959118139759',
    projectId: 'flutter-firebase-18db2',
    authDomain: 'flutter-firebase-18db2.firebaseapp.com',
    storageBucket: 'flutter-firebase-18db2.appspot.com',
    measurementId: 'G-NW5FXT04K8',
  );
}
